#!/usr/bin/env sh
set -eu

# find default python executable
if [ -z "${PYTHON:-}" ]; then
	PYTHON=python3
fi
echo "using '$PYTHON' as python executable"

# create virtual env, if needed
if [ "true" = "${USE_VENV:-true}" ]; then
	VENV=$(mktemp -d -t "kwix-build-pyinstaller.$(date +%Y-%m-%d_%H-%M-%S).XXXX")
	echo "creating python virtual environment in $VENV"
	"$PYTHON" -m venv "$VENV"
	PYTHON="$VENV/bin/python3"
	echo "now using '$PYTHON' as python executable"
fi

# run build
"$PYTHON" -m pip install 'pyinstaller==6.1.0' 'setuptools-git-versioning==1.13.5' .
"$PYTHON" -m PyInstaller pyinstaller.spec