#!/usr/bin/env sh
set -eu
VENV=$(mktemp -d -t "kwix-build-pyinstaller.$(date +%Y-%m-%d_%H-%M-%S).XXXX")
python3 -m venv "$VENV"
"$VENV/bin/pip3" install 'pyinstaller==6.1.0' 'setuptools-git-versioning==1.13.5' .
"$VENV/bin/pyinstaller" pyinstaller.spec