#!/usr/bin/env sh
set -eu

main() {
	local work_dir=$(create_temp_dir)
	echo "working directory is $work_dir"

	clean
	#build_pyproject
	#build_pyinstaller_native
	#build_appimage
	#build_pyinstaller_windows
	build_briefcase_appimage
	
}

create_temp_dir() {
	mktemp -d -t "kwix-build.$(date +%Y-%m-%d_%H-%M-%S).XXXX"
}

clean() {
	echo 'clean project directory'
	rm -rf ./build ./dist
}

build_pyproject() {
	local venv_path="$work_dir/venv/build_pyproject"
	echo "building sdist and wheel in $venv_path"
	create_venv "$venv_path"
	"$venv_path/bin/pip3" install 'build==1.0.3'
	"$venv_path/bin/pyproject-build"
}

create_venv() {
	local path="$1"
	mkdir -p "$path"
	python3 -m venv "$path"
}

build_pyinstaller_native() {
	local venv_path="$work_dir/venv/build_pyinstaller_native"
	echo "building pyinstaller executable in $venv_path"
	create_venv "$venv_path"
	"$venv_path/bin/pip3" install 'pyinstaller==6.1.0' 'setuptools-git-versioning==1.13.5' .
	"$venv_path/bin/pyinstaller" pyinstaller.spec
}

build_appimage() {
	# local venv_path="$work_dir/venv/build_appimage"
	# echo "building appimage executable in $venv_path"
	# create_venv "$venv_path"
	# "$venv_path/bin/pip3" install 'pyproject-appimage==3.0'
	# "$venv_path/bin/pyproject-appimage"
	echo 'build appimage executable not implemented'

}

build_briefcase_appimage() {
	local venv_path="$work_dir/venv/build_briefcase_appimage"
	echo "building appimage with build_briefcase executable in $venv_path"

	# sudo apt install -y pkg-config docker-buildx libcairo2-dev
	create_venv "$venv_path"
	"$venv_path/bin/pip3" install pkgconfig 'briefcase==0.3.16'

	# briefcase creae + build + package
	"$venv_path/bin/briefcase" package linux appimage
	

}

build_pyinstaller_windows() {
	echo 'build pyinstaller executable for windows not implemented'
}

main "$@"